# mairy-fullsco — listen 8081 (publish ${EXTERNAL_PHP82_PORT:-18081})
server {
    listen 8081;
    index index.php index.html;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/mairy-fullsco/public;
    client_max_body_size 40M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass external-php-82:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTPS $fcgi_https;
        fastcgi_read_timeout 300;
        send_timeout 1800;
    }

    location /blog {
        try_files $uri $uri/ /blog/index.php?$args;
    }

    location /wp/ {
        try_files $uri $uri/ /wp/index.php?$args;
    }
}
