#!/usr/bin/env bash
# Biến môi trường do docker-compose truyền (từ root .env): MYSQL_ROOT_PASSWORD, MYSQL_DB_LOCAL,
# MYSQL_DB_TEST, MYSQL_APP_USER, MYSQL_APP_PASSWORD
set -euo pipefail

: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"
: "${MYSQL_DB_LOCAL:=db_local}"
: "${MYSQL_DB_TEST:=laravel_test}"
: "${MYSQL_APP_USER:=smart}"
: "${MYSQL_APP_PASSWORD:=smart}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DB_LOCAL}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DB_TEST}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_APP_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DB_LOCAL}\`.* TO '${MYSQL_APP_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${MYSQL_DB_TEST}\`.* TO '${MYSQL_APP_USER}'@'%';

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
SQL
